### ISSUE TITLE
Highlight Samples not aligned to base waveform

### ISSUE THREAD

**Issue by ogrydziak** [fulldecent/FDWaveformView#101]
Defined
    `@IBOutlet weak var grabberContainer_view: FDWaveformView!`

In viewdidload
```
        grabberContainer_view.delegate = self
        grabberContainer_view.audioURL = uurl
        grabberContainer_view.doesAllowScrubbing = false
        grabberContainer_view.doesAllowStretch = false
        grabberContainer_view.doesAllowScroll = false
        grabberContainer_view.backgroundColor = color02
```

I have the following code attached to a button
```
            grabberContainer_view.highlightedSamples = grabberContainer_view.totalSamples / 4 ..< grabberContainer_view.totalSamples / 2
            grabberContainer_view.layoutIfNeeded()
```

http://imgur.com/WCUcETd

What happening in that pic is the full waveform in the light grey, and the result from setting highlightSamples is overlaid in the middle. To me, it looks like the overlay is an incorrect chunk of the waveform (notice that it doesn’t line up). In this SS, I had changed the colors but I just reverted it to the original to make sure I didn’t muss something up inadvertently. Also, I would just be not using this correctly, so I wouldn’t rule that out.

When I changed it to alter the bounds in the setter for highlightedSamples, everything lined up, but then I couldn’t rotate the screen properly.

This may or may not illustrate it better (attached image). 

![image](https://user-images.githubusercontent.com/662226/28374212-172997e2-6c72-11e7-817e-405fc7064e11.png)

**Comment by jonandersen** [comment]
I've noticed this as well. Looking through the code I see layoutsubviews has a few lines that doesn't seem to calculate the correct values:

  ```
 if let cachedSampleRange = cachedWaveformRenderOperation?.sampleRange, !cachedSampleRange.isEmpty && !zoomSamples.isEmpty {
            scaledX = CGFloat(cachedSampleRange.lowerBound - zoomSamples.lowerBound) / CGFloat(zoomSamples.count)
            scaledWidth = CGFloat(cachedSampleRange.last! - zoomSamples.lowerBound) / CGFloat(zoomSamples.count)    // forced unwrap is safe
            scaledHighlightedX = CGFloat((highlightedSamples?.lowerBound ?? 0) - zoomSamples.lowerBound) / CGFloat(zoomSamples.count)
            scaledHighlightedWidth = CGFloat((highlightedSamples?.last ?? 0) - zoomSamples.lowerBound) / CGFloat(zoomSamples.count)
        }
```

Calculating `scaledHighlightedWidth` should somehow make use of the lower and upper bound from the highlighted sample. I wasn't sure how all this works so I don't have a fix with zoom. I could however remove the zoom functionality and do this instead:

```
 var scaledX: CGFloat = 0.0
        var scaledWidth: CGFloat = 1.0
        var scaledHighlightedX: CGFloat = CGFloat(highlightedSamples?.startIndex ?? 0) / CGFloat(totalSamples)
        let highlightLastPortion = CGFloat(highlightedSamples?.last ?? 0) / CGFloat(totalSamples)
        var scaledHighlightedWidth: CGFloat = highlightLastPortion - scaledHighlightedX
 ```

The image is still offset a little. But the highlights works correctly with that.

**Comment by jonandersen** [comment]
@ogrydziak I've fixed it in  https://github.com/fulldecent/FDWaveformView/pull/107

**Comment by fulldecent** [comment]
Thank you for sharing. I agree that this is broken now. I have tried #107 but it is not fixing the issue for me.

**Comment by fulldecent** [comment]
I believe this is fixed now thanks to @reedom. Also released to CocoaPods and through Carthage today.
