### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by JuanPabloBoero** [fulldecent/FDWaveformView#109]
When trying to render this file, it crashes at line 266 , when doing downsample and average.
The weird thing is that if i enable the address sanitizer in the scheme it wont crash!

iOS 8.2, iPad mini, FDWaveformView 2.2.1.

[Urban Grooves 20.caf.zip](https://github.com/fulldecent/FDWaveformView/files/1293326/Urban.Grooves.20.caf.zip)

**Comment by fulldecent** [comment]
Thanks for reporting, and is this on a physical device?

**Comment by JuanPabloBoero** [comment]
Your are welcome, yes, it is an iPad mini, i believe it is a 32 bit architecture, without metal, i do not know where does the Accelerate magic happens anyway.

**Comment by fulldecent** [comment]
I am trying to find one of these devices to play with. Unfortunately this might be an architecture-specific problem.

In the meantime, have you seen the Swift 4 branch? I don't expect that this will fix anything but this is our latest code.

**Comment by fulldecent** [comment]
I have added one more commit today. Please try this version and test on a real device using the provided iOS Example app.

**Comment by fulldecent** [comment]
Please retry on the newly released version, this has fixed several rendering issues. Closing for now but please feel free to reopen if bug is still occurring.

**Comment by JPBoero** [comment]
Thanks William, will give it a try.
