### ISSUE TITLE
Cannot call value of non-function type '[AVAssetTrack]'

### ISSUE THREAD

**Issue by ShardaPrasad** [fulldecent/FDWaveformView#112]
I already Add "AVFoundation" frame work on my app. I add this library via pod. (In Objective-C Code)

![screen shot 2017-11-08 at 12 46 19 pm](https://user-images.githubusercontent.com/4727566/32536132-f4b06d12-c482-11e7-9637-7d50b8069a24.png)

**Comment by CarlosLabrado** [comment]
I have the same problem, updated the cocoa pod and this error appeared.

**Comment by fulldecent** [comment]
Thanks for sharing and confirming. Are you both using Obj-C? Please also share device (you are using a real device, right) and os, etc.

**Comment by ShardaPrasad** [comment]
@fulldecent NO i am not using any device its happens with simulator... 
Thank you

**Comment by tbass134** [comment]
`tracks` is an Array, not a function,

```
guard let assetTrack = asset.tracks.first else {
            NSLog("FDWaveformView failed to load AVAssetTrack")
            completionHandler(nil)
            return
        }
```

will fix this issue

**Comment by fulldecent** [comment]
I have added one more commit today. Please try this version and test on a real device using the provided iOS Example app.

**Comment by fulldecent** [comment]
Please try again on the latest version, a new major release is added today. This has fixed many bugs. But also, the Carthage and CocoaPods integrations are now updated, which is believe is more likely to solve the issue here.

Closing this issue now, but please feel free to reopen if the bug persists.

**Comment by adityasaravana** [comment]
Still getting this issue on the latest SPM version, "FDWaveformView failed to load AVAssetTrack". What's going on?
