### ISSUE TITLE
Unable to find a specification for `FDWaveformView (~> 3.0.1)`

### ISSUE THREAD

**Issue by AEDWIP** [fulldecent/FDWaveformView#113]
I have no idea how cocopod works. The installation directions seem a little underspecified. Any Idea what the Podfile should be?

this is the first time I have ever used cocopod

thanks
Andy

```
$ cat Podfile
target "MusicTrainerLite" do
source 'https://github.com/fulldecent/FDWaveformView.git'
platform :ios, '10.0'
pod 'FDWaveformView'
end
```

```
$ pod install --verbose
  Preparing

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-MusicTrainerLite`: (``)

Resolving dependencies of `Podfile`
[!] Unable to find a specification for `FDWaveformView`

/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.0/lib/cocoapods/resolver.rb:402:in `find_cached_set'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.0/lib/cocoapods/resolver.rb:372:in `specifications_for_dependency'
/Libra
```

**Comment by fulldecent** [comment]
Can you please share the solution you found? This will help other visitors to this page.

**Comment by AEDWIP** [comment]
Hi FullDecent

I never got this work. I delete everything and started over. attached are some notes I made about how to get it to compile how ever it does not link

see  issue [https://github.com/fulldecent/FDWaveformView/issues/114](https://github.com/fulldecent/FDWaveformView/issues/114)

Here are my notes

## Merge Notes: (I am trying to use FDWave From an Objc ios app)
* Xcode 9.3
* target iOS 10.1

pod install addes the FDWaveFormView project to our workspace how ever out of the box it does not compile

1. Need to tweak header paths
[https://stackoverflow.com/questions/12002905/ios-build-fails-with-cocoapods-cannot-find-header-files](https://stackoverflow.com/questions/12002905/ios-build-fails-with-cocoapods-cannot-find-header-files)

    - MyAppTarget Project -> target -> build settings
    - Framework search path add  $(inherited) to all the configurations 
    - Header search path $(inherited)
    - Library search path $(inherited)

2. need to enable modules
   - MyAppTarget Project -> target -> build settings
   - change CLANG_ENABLE_MODUELS to YES

3. Need to make FDWaveformView avalible in Objc
   - FDWaveformView.swift
   - change 'open class FDWaveformView:' to '@objcMembers open class FDWaveformView:'

4. add a FDWaveformView to xib using Intefacebuild
   - drag a new UIView on to window
   - go to identify inspector 'custom class'
   - Class should be 'FDWaveformView'
   - module should be 'FDWaveformView'

## Link error (never figure out how to solve this)
```
2018-04-20 11:32:48.644960-0700 MusicTrainerLite[7430:362135] Unknown class _TtC16MyAppTarget14FDWaveformView in Interface Builder file.


Showing All Errors Only
  "_OBJC_CLASS_$__TtC14FDWaveformView14FDWaveformView", referenced from:
```

5. add libFDWaveformView.a ???? this causes tons of link errors
   - MusicTrainerLite Project -> target -> general
   - my iOS app already linked against all the required frameworks
   - changing link order does not help
   - seems like a swift problem?
