### ISSUE TITLE
how to get a more distinct wave?

### ISSUE THREAD

**Issue by AEDWIP** [fulldecent/FDWaveformView#116]
I been playing around with FDWaveformView. I get a very nice graph/plot with small audio files, like maybe less than 30 seconds. Longer audio files are really dense and not so nice looking or useful.

attached is an example of long song. Free Bird is 9 min and 7 seconds long. The screen shot was captured on an iPad pro in landscape mode after zooming the width of the screen 3 times.

I tried setting AVSampleRateKey: 22050.0  and 11025.0

I also played around with downSampledLength

I tried using .linear . This seems to go into an infinite loop on my 28 sec file in WAV format.

The graph do not seem to change. I was thinking if I reduced the amount of information the graphs would look better or zoom better. My changes did not seem to help

Any suggestions would be greatly appreciated

Andy

p.s. I put a boarder around clipping and offset highlightedImage a little to get a better idea of how the code works.

![freebird-ipadpro](https://user-images.githubusercontent.com/7494191/39786727-a1a71b24-52d6-11e8-87d3-1ed994e1dd8c.jpg)

**Comment by fulldecent** [comment]
Please post this question to https://stackoverflow.com/ I think your audience will be larger there especially if you will please post the current code you are using.
