### ISSUE TITLE
please update podspec

### ISSUE THREAD

**Issue by MhmdSalah** [fulldecent/FDWaveformView#123]
the podspec says

>  s.swift_version = '4.0'

it should say 

 s.swift_version = '4.2'

this makes problem everytime i run pod update.

**Comment by fulldecent** [comment]
Thank you, I have updated this in 484d11a.

Can you please load the Pod from git (rather than the published pod) to confirm this fixes it?

**Comment by fulldecent** [comment]
Released new version which now supports 5.0.
