### ISSUE TITLE
Reloading the same audio file give different wave graph  images 

### ISSUE THREAD

**Issue by MuraliSathiyaraj** [fulldecent/FDWaveformView#129]
I am trying to load the same audio file after an refresh and through skip forward/ backward  button .But when i reload the graphview after a forward and then a backward, the audio wave image change often.

Also cannot adjust the y scaling of the wave graph 

awaiting your reply,Thanks.

**Comment by sumitpaul** [comment]
@MuraliSathiyaraj were you able to figure this out?

**Comment by MuraliSathiyaraj** [comment]
@sumitpaul no not able to figure it out

**Comment by fulldecent** [comment]
Could you please attached screen grab using LICEcap or YouTube upload?

**Comment by fulldecent** [comment]
Closing as need more information
