### ISSUE TITLE
Save State with Key

### ISSUE THREAD

**Issue by digitalfx** [fulldecent/FDWaveformView#14]
So I’m back with another feature request!

I’m currently trying to implement multiple waveformviews in the same controller, which with 3 or 4 minute tracks results in a very slow load time on older devices. That said, the AVAssets for the views are hardly ever changing, so it would be much more efficient if when the view is dismissed, the rendered png could be saved, and then on load be restored again. Presumably the view could check to see whether or not the associated avasset was the same one as when rendered just in case something has changed and it needs to re-render.

I was thinking some setable property along the lines of "savesStateWithKey" so that if a waveform had said key, it would load and save the fully zoomed out image using a key chosen by user, whenever it was created/destroyed.

Hope that makes sense?

**Comment by fulldecent** [comment]
Close as out of scope. This seems a little incompatible with the current implementation philosophy.
