### ISSUE TITLE
Dependency "FDWaveformView" has no shared framework schemes

### ISSUE THREAD

**Issue by ghost** [fulldecent/FDWaveformView#141]
I use carthage (github "fulldecent/FDWaveformView") for install FDWaveformView and I got:

*** Skipped building FDWaveformView due to the error:
Dependency "FDWaveformView" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/fulldecent/FDWaveformView/issues/new

**Comment by fulldecent** [comment]
Thank you for sharing. Is anybody else seeing this issue or have any ideas?
