### ISSUE TITLE
macOS Compatible 

### ISSUE THREAD

**Issue by wongzigii** [fulldecent/FDWaveformView#150]
Analyzing dependencies
[!] The platform of the target `` (macOS 11.0) is not compatible with `FDWaveformView (5.0.1)`, which does not support `macOS`.

**Comment by fulldecent** [comment]
Limitation for iOS removed at https://github.com/fulldecent/FDWaveformView/blob/f470d434969778ede228b8041c6679bc8ae4f4e3/Package.swift
