### ISSUE TITLE
Add range

### ISSUE THREAD

**Issue by rastaman111** [fulldecent/FDWaveformView#152]
Hey!  add new functionality so that I can dynamically set a range and edit it, as well as the ability to select it for it.  Thanks!

![image](https://user-images.githubusercontent.com/15727518/142250784-aef1f3b8-45aa-4974-bc7b-03cea2cbf860.jpeg)

**Comment by JanX2** [comment]
@rastaman111 
Is the code for this available anywhere?

**Comment by fulldecent** [comment]
This API is now supported at https://github.com/fulldecent/FDWaveformView/blob/f470d434969778ede228b8041c6679bc8ae4f4e3/Sources/FDWaveformView/FDWaveformView.swift#L68-L76
