### ISSUE TITLE
Add arbitrary selection and play only that selection

### ISSUE THREAD

**Issue by vittalk** [fulldecent/FDWaveformView#19]
Hi, 
Amazing thanks! Had a question. R u planning to add selection? For example I want to select a specific section of the file (using Pan gesture -- UIGestureRecognizerStateBegin and End in handlePanGesture()). So the user can select a section of the file with his finger (pan/touch); of course color the selection differently.
thank you very much

**Comment by fulldecent** [comment]
Closing this issue for now. I think time selection might best be implemented as a separate view on top of the waveform. There are lots of gestures involved -- FDWaveformView already handles tap, pan, and pinch, and this new UI would have additional tap and pan for each of two UI elements.
