### ISSUE TITLE
Audio from Video Files

### ISSUE THREAD

**Issue by markmunoz** [fulldecent/FDWaveformView#26]
I would like to take a video file that was created using the camera and microphone send your code the URL to said file then have it map the audio waveform.  I have implemented it and I can see it run apparently with no issues but nothing is drawn into the view.  What am I missing?

**Comment by fulldecent** [comment]
Fixed now, need to find a better way to extract audio track information from video files

**Comment by fulldecent** [comment]
![screen shot 2015-01-18 at 5 42 43 pm](https://cloud.githubusercontent.com/assets/382183/5794426/8309aea0-9f3a-11e4-92be-a0b3aa1b4e6c.png)
