### ISSUE TITLE
Waveform doesn't render for mono audio files

### ISSUE THREAD

**Issue by johnryan** [fulldecent/FDWaveformView#28]
Trying to debug, but finding that mono audio files don't render. Any suggestions?

Thanks,
John

**Comment by fulldecent** [comment]
![screen shot 2015-01-18 at 5 58 30 pm](https://cloud.githubusercontent.com/assets/382183/5794456/b95223a6-9f3b-11e4-8627-b0a8153cb4b5.png)

**Comment by johnryan** [comment]
Thanks for resolving this. Looking at the commit referenced i'm a bit confused on what has changed. I currently get the URL like this:
```
NSArray *pathComponents = [NSArray arrayWithObjects:
                                           [NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES) lastObject],
                                           @"waveFormURL.m4a",
                                           nil];
NSURL *waveFormURL = [NSURL fileURLWithPathComponents:pathComponents];
```

Is there a correct way to fix this for files that aren't in the bundle?

Thanks!

**Comment by fulldecent** [comment]
Not in the bundle... hmm. I usually use something like:

    NSURL *url = [NSSearchPathForDirectoriesInDomains(...)];
    url = url [URLByAppendingPathComponent:...]

**Comment by johnryan** [comment]
Awesome, thanks...i'll give that a try. Can you think of any reason why one of these methods would work and the other wouldnt? The url is not nil so i'd think it wouldn't make a difference.

**Comment by fulldecent** [comment]
Not sure. And also, I am easily frustrated by these bundles and document search. It gets even more hellish when you add in localized resources :-)
