### ISSUE TITLE
Way to show waveform being built during recording?

### ISSUE THREAD

**Issue by lususvir** [fulldecent/FDWaveformView#29]
Is there a way to show the waveform being built during a recording? For example, in the iOS Voice Memos app, as you record, the waveform is built. You don't have to wait until after recording to render the wave form.

**Comment by fulldecent** [comment]
How would this work? Would the entire waveform be shown each time, or would only the most recent X seconds show?

**Comment by fulldecent** [comment]
Live rendering is out of scope for this project per #2
