### ISSUE TITLE
Set Play progress does not work

### ISSUE THREAD

**Issue by etayluz** [fulldecent/FDWaveformView#33]
Hi!

I'm trying to set the play progress color as such after the waveform has been rendered and displayed:

```
-(void)endSliderDidChange
{
  self.waveformView.progressSamples = self.endSlider.value / 7.0 *  self.waveformView.totalSamples;  
}
```

Not working at all.

I've posted to StackOverflow:
http://stackoverflow.com/questions/29526559/fdwaveformview-set-play-progress-does-not-work

**Comment by etayluz** [comment]
I've also tried this:
  self.waveformView.clipping.frame = CGRectMake(0,0,320 * self.endSlider.value / MAX_LENGTH,self.waveformView.frame.size.height);
  [self.waveformView setNeedsDisplay];
  [self.waveformView setNeedsLayout];

**Comment by fulldecent** [comment]
This is working since 1.0.0
