### ISSUE TITLE
FDWaveformView.bundle" failed: No such file or directory

### ISSUE THREAD

**Issue by etamity** [fulldecent/FDWaveformView#35]
Hi,

I try to build the project which I install FDWaveformView from pod, and i got file missing.

/Users/joey/Documents/joeycodes/MacDevelop/joey/apps/Firecord/Pods/${BUILT_PRODUCTS_DIR}/FDWaveformView.bundle
building file list ... rsync: link_stat "/Users/joey/Documents/joeycodes/MacDevelop/joey/apps/Firecord/Pods/${BUILT_PRODUCTS_DIR}/FDWaveformView.bundle" failed: No such file or directory (2)
done

sent 29 bytes  received 20 bytes  98.00 bytes/sec
total size is 0  speedup is 0.00
rsync error: some files could not be transferred (code 23) at /SourceCache/rsync/rsync-45/rsync/main.c(992) [sender=2.6.9]
Command /bin/sh failed with exit code 23

Please help ..

**Comment by fulldecent** [comment]
I haven't heard much about this.

Are you using the CocoaPods approach?

**Comment by fulldecent** [comment]
Fixed in latest cocoapods and carthage builds
