### ISSUE TITLE
Output settings are not compatible with media type

### ISSUE THREAD

**Issue by senatorsfc** [fulldecent/FDWaveformView#36]
Hey,

I'm using FDWaveformView in my project to play WAV files. Seems to work fine most of the time, but I keep getting these crash reports from users using it in the app store.

NSInvalidArgumentException - *** -[AVAssetReaderTrackOutput initWithTrack:outputSettings:] Output settings are not compatible with media type 

Exact crash line is +[FDWaveformView sliceAndDownsampleAsset:track:startSamples:endSamples:targetSamples:done:] FDWaveformView.m:267

Seems like it's specifying LPCM for output settings... is there a reason why this wouldn't work?

NSDictionary *outputSettingsDict = @{AVFormatIDKey: @(kAudioFormatLinearPCM),
                                         AVLinearPCMBitDepthKey: @16,
                                         AVLinearPCMIsBigEndianKey: @NO,
                                         AVLinearPCMIsFloatKey: @NO,
                                         AVLinearPCMIsNonInterleaved: @NO};

Here's on which OS/devices the crash is happening
![screen shot 2015-07-23 at 12 13 34 pm](https://cloud.githubusercontent.com/assets/998905/8855646/47211932-3134-11e5-8bad-82f994b529f6.png)

**Comment by fulldecent** [comment]
I am not seeing the media type in the issue here, are you able to type rather than copy/paste?

**Comment by fulldecent** [comment]
Everything was rewritten in 1.0.0 and this appears to be fix. Please reopen if still broken.
