### ISSUE TITLE
Won't render a short track

### ISSUE THREAD

**Issue by solomon23** [fulldecent/FDWaveformView#37]
I have a track that's 5s long and it wont' render a waveform on it.  It gets stuck in a loop between layoutSubviews and renderAsset.  This is causing the problem:
line 181
if (self.image.image.size.width < self.frame.size.width * [UIScreen mainScreen].scale * horizontalMinimumOverdraw)
        needToRender = YES;

That always causes it to re-render.  If I remove that check, it works fine.

**Comment by fulldecent** [comment]
Could you please let me know what all of the class variables are at that time?

**Comment by solomon23** [comment]
(lldb) po [[self image] image]
<UIImage: 0x1702952c0>, {960, 168}

(lldb) po [self image]
<UIImageView: 0x15d6c10f0; frame = (0 0; 0 0); opaque = NO; userInteractionEnabled = NO; layer = <CALayer: 0x17442c9a0>>

(lldb) po [self doesAllowScroll]
NO

(lldb) po [self doesAllowStretch]
NO

(lldb) po [self doesAllowScrubbing]
NO

(lldb) po [self zoomEndSamples]
990720

(lldb) po [self zoomStartSamples]
<nil>

(lldb) po [self progressSamples]
<nil>

(lldb) po [self totalSamples]
990720

(lldb) po self
<FDWaveformView: 0x15d6ba1f0; frame = (0 12; 320 42); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x17425a880>; layer = <CALayer: 0x174620c80>>

(lldb) po [[UIScreen mainScreen] scale]
<UIScreen: 0x15d506320; bounds = {{0, 0}, {320, 568}}; mode = <UIScreenMode: 0x174221260; size = 640.000000 x 1136.000000>>

    if (self.image.image.size.width < self.frame.size.width * [UIScreen mainScreen].scale * horizontalMinimumOverdraw)

960 < 320 * 2 * 2 ( 1280) == always true

**Comment by JuanPabloBoero** [comment]
@solomon23 could you please confirm that this issue continues to happen?

**Comment by solomon23** [comment]
Sorry, I'm off that project :/

**Comment by fulldecent** [comment]
Will close for now. Can reopen if someone else has a reproducible test case.
