### ISSUE TITLE
Rewrite in Swift [HELP REQUESTED]

### ISSUE THREAD

**Issue by fulldecent** [fulldecent/FDWaveformView#41]
Do it all again in Swift

**Comment by fulldecent** [comment]
Wait until CocoaPods 1.0.0 is released

**Comment by digitalfx** [comment]
Are you just considering a straight port, or do you want to rework anything too?

**Comment by fulldecent** [comment]
I think identical API and innerworkings at this time.

**Comment by digitalfx** [comment]
Ok, sounds simple enough then.

I've made a start here: https://github.com/digitalfx/FDWaveformView/blob/swift/Pod/Classes/FDWaveformView.swift

**Comment by fulldecent** [comment]
This looks nice so far!

**Comment by fulldecent** [comment]
Done in 		919959c
