### ISSUE TITLE
Multiple colors of Progress Samples

### ISSUE THREAD

**Issue by jamrader** [fulldecent/FDWaveformView#43]
I managed to get the Waveform to have two separate `wavesColor`, but I haven't managed to create a multi-colored `progressSamples`. 

For example, if I want the middle 30 samples to be gold (regardless of whether they are included in the `progressSamples` or not), but the `wavesColor` to be black and the `progressColor` to be blue -- how would this be done? 

Thank you. I really like the project.

**Comment by jamrader** [comment]
As a somewhat related issue, how does `sampleCount` relate to `totalSamples`?

**Comment by fulldecent** [comment]
`totalSamples` is the only one in the API.

For your modification I would recommend:

 1. Calculate the the percentage start and finish of the current viewport which represents those 30 samples
 2. Duplicate the functionality of the progress view and make it on top of the view hierarchy
 3. Clip your new progress view using values calculated in 1. above

**Comment by jamrader** [comment]
OK, I may be misunderstanding something. I managed to have multiple `wavecolor`s by editing the `plotGraph` method and marking some of the `sampleCount` loops as a different color. However, with the waveform I'm dealing with, `sampleCount` is about 3,000 while `totalSamples` is 3,000,000 or so. Is this a misguided way of changing the color? 

```
for (NSInteger intSample=0; intSample<sampleCount; intSample++) {
        Float32 sample = *samples++;
        float pixels = (sample - noiseFloor) * sampleAdjustmentFactor;
        if (pixels == 0) {
            pixels = 1;
        }
        
        BOOL contained = NO;
        for (NSNumber *num in _flashSamples) {
            if (intSample < [num longValue] + 3 && intSample > [num longValue] - 3) {
                CGContextSetStrokeColorWithColor(context, [[UIColor colorWithRed:1.0f green:0.83f blue:0.0f alpha:1.0f] CGColor]);
                contained = YES;
                break;
            }
        }
        
        
        if (!contained) {
            CGContextSetStrokeColorWithColor(context, [self.wavesColor CGColor]);
        }
        
        CGContextMoveToPoint(context, intSample, centerLeft-pixels);
        CGContextAddLineToPoint(context, intSample, centerLeft+pixels);
        CGContextStrokePath(context);
    }
```

As for your step 3, would this be done in `layoutSubviews`, when setting the clipping frame?

```
self.clipping.frame = CGRectMake(0,0,self.frame.size.width*scaledProgress,self.frame.size.height);
    self.clipping.hidden = self.progressSamples <= self.zoomStartSamples;
```

**Comment by fulldecent** [comment]
Oh, that is a cool way to do it!

I was originally thinking to paint the whole thing in gold and clip to only show the part you want.

**Comment by jamrader** [comment]
Thanks! I guess the problem I am having is I can't figure out how `sampleCount` relates to `totalSamples`. In addition, I'm not sure where the progress bar is painted -- is it possible to change the colors via clipping in `layoutSubviews`?
