### ISSUE TITLE
Output problem with specific file

### ISSUE THREAD

**Issue by damianpab** [fulldecent/FDWaveformView#44]
Im using your demo ios app to show the waves related to this file: https://drive.google.com/file/d/0B898a2Y5OUavQUZUQjNfQlFzSWM/view?usp=sharing

but the output shows the waves in a constant value. 
The same file using this web audio editor https://twistedwave.com/ show the correct output

Is there any special configuration that in the demo app to change the output? Thanks

**Comment by fulldecent** [comment]
Can you please attached screenshots of both waveforms and any log output.

**Comment by damianpab** [comment]
Image using your demo:
![screen shot 2016-03-15 at 10 50 35 am](https://cloud.githubusercontent.com/assets/17597883/13779972/3f5b26a8-ea9c-11e5-88f5-d923f8524d98.png)

Image using an external editor like https://twistedwave.com/online/ : 

![screen shot 2016-03-15 at 10 54 57 am](https://cloud.githubusercontent.com/assets/17597883/13780052/90cf381c-ea9c-11e5-94ea-6f8afd21b5df.png)

**Comment by fulldecent** [comment]
Where did this recording come from? This waveform has a large DC offset, please see

http://manual.audacityteam.org/o/man/dc_offset.html

Audacity can fix this waveform with Normalize / Remove DC offset. And a better way for this specific waveform is to do High Pass filter / 10 Hz / -48 dB per octave.

I believe FDWaveform behavior in this instance is correct.
