### ISSUE TITLE
Get it working for online music 

### ISSUE THREAD

**Issue by aliachour** [fulldecent/FDWaveformView#50]
how to get this working for online url music? it only works with saved music but i want it to work with online too, any ideas?

**Comment by fulldecent** [comment]
Please use Alamofire to download and then process locally. Downloading and caching remote audio files will not be in scope of this project.

**Comment by nlabhart** [comment]
Has the scoped changed for this yet ? :)

**Comment by fulldecent** [comment]
No. Downloading files will not be in scope for FDWaveformView.
