### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by fulldecent** [fulldecent/FDWaveformView#55]
Should have

    lines = cd_stats[:total_lines_of_code].to_f
    expectations = cd_stats[:total_test_expectations].to_f
      0.045 < (expectations / lines)

**Comment by haydenholligan** [comment]
Could this issue be made more clear? Not entirely sure what to do here.

**Comment by fulldecent** [comment]
Just need to add a few tests.

**Comment by fulldecent** [comment]
Fixed with 3b0621975208559bc9454f0ad369d119b047aace
