### ISSUE TITLE
Issue in change sound waves single color to Gradient color

### ISSUE THREAD

**Issue by narenderkumarrajput** [fulldecent/FDWaveformView#59]
Hello Developer,

I am using this code for create sound waves in my project it is perfectly fine. But as par my requirements I want change waves color, single color to gradient color. like this
[http://www.sciencealert.com/images/articles/processed/sound-waves_1024.jpg](Image)

and more I think this method help you. please have a look inti this
- (void)plotLogGraph:(NSData *) samplesData
        maximumValue:(Float32) normalizeMax
        mimimumValue:(Float32) normalizeMin
         sampleCount:(NSInteger) sampleCount
         imageHeight:(float) imageHeight
                done:(void(^)(UIImage *image, UIImage *selectedImage))done
 

Please do helpful.
Regards,
Narender kumar

**Comment by fulldecent** [comment]
Closing as out of scope. Alternate rendering styles is currently out of scope for this project.
