### ISSUE TITLE
Version 1.0 is not available as a Pod

### ISSUE THREAD

**Issue by JuanPabloBoero** [fulldecent/FDWaveformView#61]
Page says 1.0.0 but it is not there... if left without number it retrieves version 0.3.1

**Comment by fulldecent** [comment]
Hmm, I am having trouble pushing the spec. Have you been able to get the spec working locally? I am trying to figure out what went wrong here.

**Comment by JuanPabloBoero** [comment]
i am finally using 0.3.1 until 1.0 is available, in case it can helps, i was targeting iOS 9.1...
