### ISSUE TITLE
Not drawing

### ISSUE THREAD

**Issue by JuanPabloBoero** [fulldecent/FDWaveformView#62]
Version 1.0.1 is not visualizing when trying to play a sound shorter than 2 secs, obviously there is something with the frame calculation since the image frame printed by the console is  minus one pixel of width:

(9.0, 6.0, 84.0, 30.0) -- (-0.00151425, 0.0, 0.00151425, 30.0)

Weird thing is that is the same value of the x position.

With 0.3.1 version it works fine.

**Comment by rcholic** [comment]
I have the same problem with ver 1.0.1.

**Comment by fulldecent** [comment]
Thanks for reporting. Can you please confirm that everything is working fine for you for longer sound tracks?

**Comment by nikfil89** [comment]
Not working for me too. Even your example doesn't draw anything.

**Comment by fulldecent** [comment]
@nikfil89 @rcholic @JuanPabloBoero Thank you! I think this is corrected in master. Could I please ask you to check if that is working.

**Comment by digitalfx** [comment]
Master is now working for me.

**Comment by fulldecent** [comment]
Thank you, marking resolved

**Comment by fulldecent** [comment]
Thanks for your patience. Closed and released new version.

**Comment by JuanPabloBoero** [comment]
It is fully working, thank you, i love the pod.
