### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by JuanPabloBoero** [fulldecent/FDWaveformView#76]
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '*** -[AVAssetReader addOutput:] cannot add an output that has already been added to another AVAssetReader'

I use the pod for a sampler app, where you shot many sounds quickly and update the wave form analyzer, from time to time i got that exception, let me paste where it did happen: 

```
        let readerOutput = AVAssetReaderTrackOutput(track: assetTrack, outputSettings: outputSettingsDict)
        readerOutput.alwaysCopiesSampleData = false
        reader.add(readerOutput)  <<<--- HERE
```

**Comment by fulldecent** [comment]
Hmm... I have not seen this before. Has anyone else seen this?

**Comment by JuanPabloBoero** [comment]
You can reproduce the exception, by updating the waveform very fast with different sounds.

**Comment by fulldecent** [comment]
Are you talking about updating the asset while the waveform is rendering?

**Comment by JuanPabloBoero** [comment]
I do not know for sure, i have 9 pads, each pad has a sound assigned, when i press a pad i update the waveform (one view) according to the sound assigned to that pad, if i press just one pad repeatedly very fast, it works fine, if i start multitouching, firing many pads at the same time (updating one instance of FDWaveFormView), it crashes, what i am thinking of right now as a workaround is to implement some kind of logic in the delegate callbacks or create an instance of FDWaveFormView for each pad to see if it is an issue of concurrence.

**Comment by PavelKandziuba** [comment]
Also have that bug (((

**Comment by PavelKandziuba** [comment]
As a quick fix that helped reader.canAdd(readerOutput) == true. That is preventing crash.
But at least one cell in tableview with audio cells (7 on screen) with 20-30 % will be not rendered

**Comment by fulldecent** [comment]
Hello all, I moved the `AVAssetReader` into the instance class so that it is not recreated.

I believe this should fix the problem. If not, could you please reopen.
