### ISSUE TITLE
Processing large audio files produces an empty waveform image

### ISSUE THREAD

**Issue by ospr** [fulldecent/FDWaveformView#78]
There are two related bugs in current master:

- The call to `vDSP_desamp` when processing samples will only process a portion of the samples in `processingBuffer` (`samplesPerPixel` * `downSampledLength` samples which is most likely less than `processingBuffer.count`). The final samples are then just thrown away on the next sample processing iteration.
- For larger audio files where `samplesToProcess` is less than `samplesPerPixel` the `downSampledLength` becomes zero and we end up with an empty `outputSamples` array at the very end resulting in an empty waveform image.

(I could break these out into two separate issues, but I have a fix incoming that will address both)

**Comment by ospr** [comment]
Fix for this in pr: https://github.com/fulldecent/FDWaveformView/pull/79

**Comment by fulldecent** [comment]
Fixed in #79.
