### ISSUE TITLE
Last commits not available via CocoaPods

### ISSUE THREAD

**Issue by JuanPabloBoero** [fulldecent/FDWaveformView#81]
I am not getting the latest code when installing via CocoaPods, i realized when my console was printing errors about modifying autolayout from background threads.

Also, do not know if has something to do, but CI Travis is failing for the latest commits.

Thanks.

**Comment by fulldecent** [comment]
Thanks for the reminder. Just published 2.0.1: https://github.com/fulldecent/FDWaveformView/releases/tag/2.0.1 to CocoaPods.
