### ISSUE TITLE
Is there any way to pause the animation??

### ISSUE THREAD

**Issue by JeromeTW** [fulldecent/FDWaveformView#82]
I use the following code. Is there any way to pause the animation?? Thx!
`
UIView.animate(withDuration: audioPlayer!.duration) {
	self.waveView.progressSamples = self.waveView.totalSamples
}
`

**Comment by fulldecent** [comment]
There is discussion here of your question:

http://stackoverflow.com/questions/3211065/how-to-pause-and-resume-uiview-animation
