### ISSUE TITLE
Use ranges when we can [RFQ]

### ISSUE THREAD

**Issue by fulldecent** [fulldecent/FDWaveformView#86]
This breaks API so we need to:

- [ ] Implement new API
- [ ] Reimplement old API utilizing new API
- [ ] Mark old API as deprecated

And then create a new issue:

- [ ] Remove deprecated API
- [ ] Bump major version

----

## Changes

- [ ] Change `zoomSamples*` to a range (this change is cosmetic)
   - Remove `zoomStartSamples`
   - Remove `zoomEndSamples`
   - Add `zoomSamples: CountableClosedRange<Int>`
- [ ] Change `highlightedSamples` to a range (related: #42, #43 ) (this change now allows highlighting from somewhere that does not start at zero)
   - Remove `progressSamples`
   - Add `highlightedRange: CountableClosedRange<Int>?`
   - Rename `progressColor` to `highlightColor`

----

## Implementation notes

Ranges have a few nifty methods that we can use:

* `func clamped(to: Range<Bound>)`
* `func contains(Bound)`
* `func overlaps(Range<Bound>)`

**Comment by fulldecent** [comment]
Hopefully we can work on #80 before this.

**Comment by fulldecent** [comment]
Hello, review and provide feedback on this one!?!?!

**Comment by fulldecent** [comment]
Hello world. Please provide some feedback here.

**Comment by pixlwave** [comment]
This change certainly makes sense, good to see the progress of this project. #80 looks like a pretty mega change to implement first though.

**Comment by fulldecent** [comment]
@pixlwave Thanks for the feedback. We are making progress on #80, we now have a merge commit so more people can easily test it.

**Comment by fulldecent** [comment]
Version bump discussed in #97
